// apps/frontend/src/routes/(app)/components/link-breadcrumbs.svelte
<script lang="ts">
	import { page } from '$app/state';
	import * as Breadcrumb from '$lib/components/ui/breadcrumb/index.js';
	import { Scrollbar } from '$lib/components/ui/scroll-area';
	import ScrollArea from '$lib/components/ui/scroll-area/scroll-area.svelte';
	import { Slash } from '@lucide/svelte';

	type Item = {
		label: string;
		href?: string;
	};

	function pathnameToItems(pathname: string): Item[] {
		const parts = pathname.split('/').filter((part) => part !== '');
		const items: Item[] = [];

		parts.forEach((part, index) => {
			const fullPath = `/${parts.slice(0, index + 1).join('/')}`;
			const label = part
				.split('-')
				.map((word, idx) => (idx === 0 ? word.charAt(0).toUpperCase() + word.slice(1) : word))
				.join(' ');

			items.push({ label, href: fullPath });
		});

		return items;
	}

	let items = $derived(pathnameToItems(page.url.pathname));
</script>

<ScrollArea class="w-px grow py-1.5">
	<Breadcrumb.Root>
		<Breadcrumb.List class="flex-nowrap">
			{#each items as item, idx (item.label)}
				<Breadcrumb.Item class="whitespace-nowrap">
					<Breadcrumb.Link href={item.href}>
						{item.label}
					</Breadcrumb.Link>
				</Breadcrumb.Item>
				{#if idx !== items.length - 1}
					<Breadcrumb.Separator>
						<Slash />
					</Breadcrumb.Separator>
				{/if}
			{/each}
		</Breadcrumb.List>
	</Breadcrumb.Root>
	<Scrollbar orientation="horizontal" />
</ScrollArea>

// components/link-breadcrumbs.tsx
"use client";

import {
  Breadcrumb,
  BreadcrumbItem,
  BreadcrumbLink,
  BreadcrumbList,
  BreadcrumbSeparator,
} from "@/components/ui/breadcrumb";
import { usePathname } from "next/navigation";
import { Fragment } from "react";
import { ScrollArea, ScrollBar } from "./ui/scroll-area";

type Item = { label: string; href?: string };

function pathnameToItems(pathname: string): Item[] {
  const parts = pathname.split("/").filter((part) => part !== "");
  const items = [
    ...parts.map((part, index) => {
      if (index === parts.length - 1) {
        part = part.split("?")[0];
      }
      return {
        label: part
          .split("-")
          .map((word, idx) =>
            idx === 0 ? word.charAt(0).toUpperCase() + word.slice(1) : word
          )
          .join(" "),
        href: `/${parts.slice(0, index + 1).join("/")}`,
      };
    }),
  ];
  return items;
}

export function LinkBreadcrumbs() {
  const pathname = usePathname();
  const allItems = pathnameToItems(pathname);
  const items =
    allItems.length > 1 ? allItems.slice(1, allItems.length) : allItems;

  return (
    <ScrollArea>
      <Breadcrumb>
        <BreadcrumbList className="flex-nowrap py-2.5">
          {items.map((item, index) => (
            <Fragment key={index}>
              <BreadcrumbItem>
                <BreadcrumbLink href={item.href} className="whitespace-nowrap">
                  {item.label}
                </BreadcrumbLink>
              </BreadcrumbItem>
              {index < items.length - 1 && <BreadcrumbSeparator />}
            </Fragment>
          ))}
        </BreadcrumbList>
      </Breadcrumb>
      <ScrollBar orientation="horizontal" />
    </ScrollArea>
  );
}
