// app/(app)/exercise-splits/create/page.tsx
import { TypographyH1 } from "@/components/typography/h1";
import { TypographyH2 } from "@/components/typography/h2";
import { Button } from "@/components/ui/button";
import { ChevronRightCircleIcon } from "lucide-react";
import Link from "next/link";

export default function ExerciseSplitsCreatePage() {
  return (
    <>
      <TypographyH1>Create split</TypographyH1>
      <TypographyH2>Choose template</TypographyH2>
      <div className="flex flex-col grow"></div>
      <Button asChild>
        <Link href="/exercise-splits/create/basics">
          Start from scratch
          <ChevronRightCircleIcon />
        </Link>
      </Button>
    </>
  );
}

// src/routes/(app)/exercise-splits/create/+page.svelte
<script>
	import H1 from '$lib/components/typography/h1.svelte';
	import H2 from '$lib/components/typography/h2.svelte';
	import Button from '$lib/components/ui/button/button.svelte';
	import { ChevronRightCircleIcon } from 'lucide-svelte';
</script>

<H1>Create split</H1>
<H2>Choose template</H2>

<div class="flex grow flex-col"></div>

<Button href="/exercise-splits/create/basics">Start from scratch <ChevronRightCircleIcon /></Button>
